In [1]:
import cv2
import numpy as np
import os
from sklearn.neighbors import KNeighborsClassifier as Knn

In [2]:
model=cv2.CascadeClassifier("raw.githubusercontent.com_opencv_opencv_4.x_data_haarcascades_haarcascade_frontalface_alt.xml")
camera=cv2.VideoCapture(0)
offset=30

In [3]:
dataset_path="./data/"
faceData=[]
labels=[]
nameMap={}
classId=0

for f in os.listdir(dataset_path):
    if f.endswith(".npy"):
        nameMap[classId]=f[:-4]
        dataItem=np.load(dataset_path+f)
        m=dataItem.shape[0]
        faceData.append(dataItem)
        target=classId*np.ones((m,))
        classId+=1
        labels.append(target)
X=np.concatenate(faceData,axis=0)
Y=np.concatenate(labels,axis=0).reshape((-1,1))

In [ ]:
mod=Knn(4)
mod.fit(X,Y)
while True:
    success,img=camera.read()
    if not success:
        print("Reading Camera Failed")
        break
    faces=model.detectMultiScale(img,1.3,2)
    print(faces)
    if len(faces)>0:
        for f in faces:
            x,y,w,h=f
            cropped_face=img[y-offset:y+h+offset,x-offset:x+w+offset]
            cropped_face=cv2.resize(cropped_face,(100,100))
            classPredicted=int(mod.predict(cropped_face.flatten().reshape(1,-1)))
            namePredicted=nameMap[classPredicted]
            cv2.putText(img,namePredicted,(x,y-10),cv2.FONT_HERSHEY_SIMPLEX,1,(250,250,0),2,cv2.LINE_AA)
            cv2.rectangle(img,(x,y),(x+w,y+h),(250,250,50),2)
    cv2.imshow("Prediction Window",img)
    key=cv2.waitKey(1)
    
    if key==ord('q'):
        break
camera.release()
cv2.destroyAllWindows()

C:\Users\njuya\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[306 145 212 212]]
[[298 154 219 219]]
[[283 160 230 230]]
[[283 160 230 230]]
[[294 183 200 200]]
[[276 188 212 212]]
[[276 188 212 212]]
[[277 217 194 194]]
[[278 234 189 189]]
[[278 234 189 189]]
[[279 239 186 186]]
[[284 234 188 188]]
[[284 234 188 188]]
[[288 232 188 188]]
[[290 223 188 188]]
[[298 222 178 178]]
[[298 222 178 178]]
[[302 222 172 172]]
[[294 220 185 185]]
[[292 219 181 181]]
[[300 220 173 173]]
[[300 221 174 174]]
[[300 214 179 179]]
[[294 219 178 178]]
[[294 213 185 185]]
[[292 212 188 188]]
[[295 220 177 177]]
[[310 230 154 154]]
[[302 228 163 163]]
[[302 225 163 163]]
[[288 222 179 179]]
[[292 224 175 175]]
[[289 222 179 179]]
[[286 221 183 183]]
[[286 221 183 183]]
[[286 223 183 183]]
[[286 223 183 183]]
[[287 226 175 175]]
[[287 226